version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  web-dashboard:
    build: ./web-dashboard
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bluecarbon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abhi5566
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfsdata:/data/ipfs

volumes:
  pgdata:
  ipfsdata:
